"""typo in user table

Revision ID: feac9697634e
Revises: 3a1980a5d7bf
Create Date: 2025-08-04 20:11:51.590909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'feac9697634e'
down_revision = '3a1980a5d7bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))
        batch_op.drop_index(batch_op.f('ix_user_emal'))
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.drop_column('emal')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emal', sa.VARCHAR(length=120), nullable=False))
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.create_index(batch_op.f('ix_user_emal'), ['emal'], unique=1)
        batch_op.drop_column('email')

    # ### end Alembic commands ###
